### ISSUE TITLE
compilation on ARM fails

### ISSUE THREAD

**Issue by ghost** [gekomad/Cinnamon#2]
Hey,

I got the idea to compile Cinnamon on my Raspberry Ubuntu Mate 15-10 armv7 based.

To compile I used: "make cinnamon-generic32" 

At first compilation fails as the switch "-m32" is unknown. So I removed it from Makefile section cinnamon-generic32.

Now compilation starts perfectly. However, not very long. It generates plenty of this error:

> error: narrowing conversion of ‘-8’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]

and of course fails.

Maybe an idea how to get around?

**Comment by gekomad** [comment]
Hi,
re-download source and type `make cinnamon-ARM`
