### ISSUE TITLE
Setting Hash doesn't work under Cute Chess

### ISSUE THREAD

**Issue by tpoppins** [gekomad/Cinnamon#46]
Setting hash size works in console , e.g. `setoption name Hash value 512` makes Cinnamon use ~ 518 MB (Commit Size in Task Manager). However under Cute Chess GUI (own [2018-01-18](https://www.mediafire.com/file/93ilk4e06c9ux8c/cutechess-20190118-x64.zip/file) dev build) Cinnamon's Commit Size is only ~ 103 MB despite proper commands being exchanged.

```
< id name Cinnamon 2.1
< id author Giuseppe Cannella
< option name Hash type spin default 64 min 1 max 1000
< option name Clear Hash type button
< option name Nullmove type check default true
< option name Book File type string default cinnamon.bin
< option name OwnBook type check default false
< option name Ponder type check default false
< option name Threads type spin default 1 min 1 max 64
< option name GaviotaTbPath type string default <empty>
< option name GaviotaTbCache type spin default 32 min 1 max 1024
< option name GaviotaTbScheme type combo default cp4 var none var cp1 var cp2 v
< option name TB Pieces installed type combo default 3 var none var 3 var 4 var
< option name TB Restart type button
< option name PerftThreads type spin default 1 min 1 max 64
< option name PerftHashSize type spin default 0 min 0 max 100000
< option name PerftDumpFile type string
< uciok
> setoption name Book File value cinnamon.bin
> setoption name GaviotaTbPath value e:\gaviota
< cinnamon.bin not found
> setoption name GaviotaTbScheme value cp4
< file not found e:\gaviota
> setoption name Hash value 512
> setoption name Nullmove value true
> setoption name OwnBook value false
> setoption name PerftDumpFile
> setoption name PerftHashSize value 0
> setoption name PerftThreads value 1
> setoption name TB Pieces installed value 5
> setoption name Threads value 1
> isready
< Unknown command: setoption name PerftDumpFile
< readyok
> ucinewgame

```

The previous version, 2.0, exhibits the same behavior.

**Comment by gekomad** [comment]
here the link http://cinnamonchess.altervista.org/cinnamon_2.2.beta.exe

**Comment by tpoppins** [comment]
The problem persists with the new exec. I think the solution I proposed in #45 -- disabling automatic printing of version info and the ASCII picture on startup -- should solve it.

**Comment by tpoppins** [comment]
The beta3 exec solved the TB access issue. However, setting Hash via GUI still doesn't work -- Cinnamon's Commit Size stays around 100 MB. Curiously, renaming "**o**ption name Threads" in the exec to "**x**ption name Threads" fixes it. A pretty little puzzle, this.

**Comment by gekomad** [comment]
this https://github.com/gekomad/Cinnamon/blob/_test_/fix_46_hash/cinnamon2.2_fix_46_hash.exe
should fix hash size issue

**Comment by tpoppins** [comment]
Indeed it does. Thank you, Giuseppe, you've done a terrific job in the past 24 hours!

Waiting now for the official release so we can start testing it.

Tirsa@CCRL

**Comment by gekomad** [comment]
Thank for your great job, I'ww release as soon as possible.
