### ISSUE TITLE
Cinnamon 2.1 sacs it’s queen for nothing on Picochess.

### ISSUE THREAD

**Issue by ScallyBag** [gekomad/Cinnamon#47]
Hi Giuseppe,

I’ve been trying out your new version of Cinnamon 2.1 in Picochess.
It was paired agains Tasc 2.2, Cinnamon has the Black pieces in a 90 seconds per move game.

This is the move sequence:

1.e4 c5 2.Nf3 e6 3.d4 cxd4 4.c3 dxc3 5.Nxc3 Nc6 6.Bc4 Qc7 7.Qe2 Nf6 8.h3 Bd6 9.Nb5 Bb4+ 10.Bd2 Bxd2+ 11.Qxd2 Qb6 12.Nd6+ Ke7 13.Rd1 Qxf2+ ?? 14.Kxf2 Nxe4+ 15 Nxe4

I have replayed the game several times at different time intervals, but Cinnamon gives it’s queen away every time at move 13?

Here’s the FEN before Blacks bad move:

r1b4r/pp1pkppp/1qnNpn2/8/2B1P3/5N1P/PP1Q1PP1/3RK2R b K - 4 13

I was using your Raspberry Pi Binary, I also compiled it myself with the same results.

Thanks,

Alan Cooper.

**Comment by gekomad** [comment]
try this version
https://drive.google.com/file/d/1n0Glkq_XE3U6XaGnkhHxY4xZhY-z6mGC/view?usp=sharing

**Comment by ScallyBag** [comment]
Hi Giuseppe,

Thanks for the quick response, it’s still playing the same Queen sac. After 9.Nb5 it seems Cinnamon believes it’s mate in 1 against it, hence the checks and Queen sac.

Thanks,

Al.

**Comment by gekomad** [comment]
I can't replicate the issue, please check this
https://drive.google.com/file/d/1Dqndr56Kq7mxydt2dauqRlQE8-wYmLp7/view?usp=sharing
 thanks

**Comment by ScallyBag** [comment]
Hi Giuseppe,

It’s still playing the same Queen sacrifice in all 3 time controls within Picochess, that’s Fischer, game in x or move in x. However outside of Picochess running your engine natively via ./cinnamon, it plays a different move when I give it the FEN of the position.

I’m at a loss to think what it might be?

Thanks,

Al.

**Comment by gekomad** [comment]
I think the issue is on trasposition table

Il ven 5 apr 2019, 16:01 Al ‘Scally’ Cooper <notifications@github.com> ha
scritto:

**Comment by ScallyBag** [comment]
Ok, if it’s any help I just compiled Cinnamon v2.0 and it doesn’t happen on that version, all seems well.

Al.

**Comment by gekomad** [comment]
How can I replicate the moves?


Il ven 5 apr 2019, 19:04 Al ‘Scally’ Cooper <notifications@github.com> ha
scritto:

**Comment by ScallyBag** [comment]
I can’t think how. Cinnamon v2.1 & v2.2 produce the Queen problem only on Picochess not runnng it stand alone via ./cinnamon. 

Your old version 2.0 works perfectly fine as tried again this afternoon.

Al.

**Comment by gekomad** [comment]
@ScallyBag I think I found the problem can you re-check ? here new exe http://cinnamonchess.altervista.org/tmp/cinnamon22a
thanks

**Comment by ScallyBag** [comment]
Hi Giuseppe,

Thanks for the new binary, unfortunately it’s still happening ....

https://i.postimg.cc/6ykGRY5P/5-EC0-BE24-2493-4-F2-C-B304-0-BA81-F16-CBA4.jpg

Al.

**Comment by tpoppins** [comment]
Cannot reproduce with the Windows x64 v2.2a binary under Cute Chess GUI using the TC of 90s/move. Even with hash as low as 1MB Cinnamon finds 13...Qa5 at d=8 and sticks with it.

Must be a bug with the Raspberry P binary.

**Comment by ScallyBag** [comment]
Hi Giuseppe,

I compiled v2.2a myself and the Queen sac no longer happens within Picochess.

Thanks very much for your patience and help.

Al.

**Comment by gekomad** [comment]
Great. thanks

**Comment by LocutusOfPenguin** [comment]
so, is this solved now? What was the (real) cause of these problems?
Shouldnt be related on compiling. So, i worry abit (for picochess).

Jürgen

**Comment by gekomad** [comment]
yes, It seems a compilation problem

**Comment by LocutusOfPenguin** [comment]
i meant:
- if solved, should be closed.
- i would feel better, if the cause is clear! Sadly, the old bins (mentioned above) no longer available. So, if y take an old version => error, and with 2.2A no longer (13.Apr).
For me - when i read the above text, it seems to be a mixture of compile, some source code bugs (say: transposition table) or no problem on windows.

Thats strange. But OK, i dont need to care too much.

Yours, Jürgen
