### ISSUE TITLE
Sources for libgtb.a?

### ISSUE THREAD

**Issue by fonkap** [gekomad/Cinnamon#5]
I'm trying to build Cinnamon with VStudio and Im having a tough time...

One problem I am being unable to workaround I think is that libgtb.a is built with gcc and for gcc and it is not linking well using VStudio, I have some errors like:

unresolved external symbol _sprintf referenced in function _tb_init	- libgtb.a(gtb-probe.o)
unresolved external symbol ___chkstk_ms referenced in function _fd_openit - libgtb.a(gtb-probe.o)

I wonder if I may compile libgtb by myself and use it to link Cinnamon.

Thanks in advance.

**Comment by gekomad** [comment]
Cinnamon is not compilable with MS compiler. You should use clang or gcc in command line or in VStudio you can switch compiler

**Comment by fonkap** [comment]
Ok, I think I may try code blocks.

Thanks for your response.
