### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by itotallyrock** [gekomad/Cinnamon#50]
It looks like [the website](http://cinnamonchess.altervista.org/) you have linked is not hosted anymore.   Either taken down, expired or something I don't know.  I have used your site for its bitboard calculator almost once a week for a few months, to create unit tests and other metrics for my own engine.  I imagine there are more like me who would like to still have access to your site, regardless of their use case.

**Comment by gekomad** [comment]
new page is here https://gekomad.github.io/Cinnamon/BitboardCalculator/
