### ISSUE TITLE
butterfly bug

### ISSUE THREAD

**Issue by ghost** [gekomad/Cinnamon#52]
Hello,version 0.3.3 linux does not want to launch.
![Capture d’écran du 2021-04-18 11-37-34](https://user-images.githubusercontent.com/77933011/115141240-73212a00-a03b-11eb-932b-9e32986ed5da.png)

I am under manjaro gnome
and I use pychess.
I also noticed that the butterfly 0.5 and 0.6 versions freeze in the middle of the game.

**Comment by gekomad** [comment]
Did you try to recompile?

**Comment by ghost** [comment]
no.
I don't know how we do it.

**Comment by gekomad** [comment]
download source zip, unzip it, with a terminal go in src folder and write `make`

**Comment by ghost** [comment]
It works, but it freezes from time to time.

**Comment by gekomad** [comment]
sorry, butterfly is a very old version, I can't debug it.
