### ISSUE TITLE
Time forfeits

### ISSUE THREAD

**Issue by SzotsGabor** [gekomad/Cinnamon#53]
Hi Giuseppe,

I have just finished a 416 game gauntlet with version 2.4 and 54 times Cinnamon exceeded time. That is exceptional with the 2 min + 1 s time control I use. The games were played under Arena, a GUI notorious of time forfeits but still...
I have a 64-bit Win 10, Intel i5-4690K CPU. I used the Intel BMI2 compile.

It's a pity because it seems that this version brings a nice improvement otherwise.

**Comment by gekomad** [comment]
Thanks Gabor, can you provide me the log file?

**Comment by SzotsGabor** [comment]
> 
> 
> Thanks Gabor, can you provide me the log file?

Unfortunately I have not saved the Arena debug.

**Comment by SzotsGabor** [comment]
I am running a new tournament. No time forfeits so far (56 games). I have the suspicion that time forfeits occur while I play a logical game which measures time. I'll come back to you if something less nebulous turn up.

**Comment by SzotsGabor** [comment]
The second tournament with more than 500 games has finished. There were only 2 time forfeits. I was more careful this time, not playing as much as before. I think the issue may be closed.

**Comment by gekomad** [comment]
Thanks Gabor
