### ISSUE TITLE
v2.4 change of speed and playing style !?

### ISSUE THREAD

**Issue by tissatussa** [gekomad/Cinnamon#55]
while testing your new Cinnamon v2.4 i discovered it easily reaches depth 17 within 30 seconds (on my basic laptop) although v2.3.4 just reaches depth 14 !? Another thing : 2.4 seems to favor 1.e3 in the starting position while 2.3.4 prefers 1.Nf3 (at first) .. 

what did you change for the engine to behave like this ?
( i think 1.e3 can be a perfect move ! )

**Comment by gekomad** [comment]
Hi, I changed a lot of code so I can't say exactly what improve the engine, Reverse Futility Pruning and badCapture (in quescence search) definitely affect.

**Comment by tissatussa** [comment]
thanks.
anyhow, it seems Cinnamon is improved !
[ you can close this "issue" now ]
