### ISSUE TITLE
elo force

### ISSUE THREAD

**Issue by ghost** [gekomad/Cinnamon#56]
Good morning,
in the next version to come, would it be possible to put a force setting ?

**Comment by gekomad** [comment]
Hi @laripette in next version it is not scheduled,
you can limit the strength disabling null move with uci command `setoption name Nullmove value false`
bye

**Comment by ghost** [comment]
indeed, the engine loses about 200elo. it must be in the 2000elo range when i disable null move.

Thanks for the tip.
