### ISSUE TITLE
Can you build a Korean chess engine?

### ISSUE THREAD

**Issue by cjssh1002** [gekomad/Cinnamon#58]

**Comment by gekomad** [comment]
I don't know it, where are the rules?

**Comment by cjssh1002** [comment]
Chinese chess Xiangqi Many engines exist. similar to Korean chess However, in Korean chess(Janggi), only the fairy-stockfish engine exists.
So, if you develop it first, you can preempt it.
I'll give you a site you can refer to.
And I am a janggi player. So I can help you.

https://en.wikipedia.org/wiki/Janggi
https://www.pychess.org/variants/janggi
https://github.com/cutechess/cutechess/issues/564
